import {
  bootstrapLogo,
  cssLogo,
  htmlLogo,
  jsLogo,
  reactLogo,
  sassLogo,
  figmaLogo,
  gitLogo,
  githubLogo,
  nodeLogo,
  npmLogo,
  discordJsLogo,
  wordpressLogo,
  cypressLogo,
  jestLogo,
  tailwindLogo,
  viteLogo,
  vscLogo,
  flutterLogo,
} from "../assets/logos/logoExports";

const icons = [
  { src: bootstrapLogo, name: "Bootstrap" },
  { src: reactLogo, name: "React" },
  { src: htmlLogo, name: "HTML5" },
  { src: cssLogo, name: "CSS3" },
  { src: jsLogo, name: "JavaScript" },
  { src: nodeLogo, name: "Node.js" },
  { src: sassLogo, name: "Sass" },
  { src: figmaLogo, name: "Figma" },
  { src: gitLogo, name: "Git" },
  { src: githubLogo, name: "GitHub" },
  { src: npmLogo, name: "npm" },
  { src: discordJsLogo, name: "Discord.js" },
  { src: wordpressLogo, name: "WordPress" },
  { src: cypressLogo, name: "Cypress" },
  { src: jestLogo, name: "Jest" },
  { src: tailwindLogo, name: "Tailwind CSS" },
  { src: viteLogo, name: "Vite" },
  { src: vscLogo, name: "VS Code" },
  { src: flutterLogo, name: "Flutter" },
];

export default icons;
