import {
  bootstrapLogo,
  cssLogo,
  htmlLogo,
  jsLogo,
  reactLogo,
  sassLogo,
  figmaLogo,
  gitLogo,
  githubLogo,
  nodeLogo,
  npmLogo,
  discordJsLogo,
  wordpressLogo,
  cypressLogo,
  jestLogo,
  tailwindLogo,
  viteLogo,
  vscLogo,
  flutterLogo,
} from "../assets/logos/logoExports";

const icons = [
  {
    src: bootstrapLogo,
    name: "Bootstrap",
    url: "https://getbootstrap.com/",
    alt: "Bootstrap Logo",
  },
  {
    src: reactLogo,
    name: "React",
    url: "https://reactjs.org/",
    alt: "React Logo",
  },
  {
    src: htmlLogo,
    name: "HTML5",
    url: "https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5",
    alt: "HTML5 Logo",
  },
  {
    src: cssLogo,
    name: "CSS3",
    url: "https://developer.mozilla.org/en-US/docs/Web/CSS",
    alt: "CSS3 Logo",
  },
  {
    src: jsLogo,
    name: "JavaScript",
    url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    alt: "JavaScript Logo",
  },
  {
    src: nodeLogo,
    name: "Node.js",
    url: "https://nodejs.org/en/",
    alt: "Node.js Logo",
  },
  {
    src: sassLogo,
    name: "Sass",
    url: "https://sass-lang.com/",
    alt: "Sass Logo",
  },
  {
    src: figmaLogo,
    name: "Figma",
    url: "https://www.figma.com/",
    alt: "Figma Logo",
  },
  { src: gitLogo, name: "Git", url: "https://git-scm.com/", alt: "Git Logo" },
  {
    src: githubLogo,
    name: "GitHub",
    url: "https://github.com",
    alt: "GitHub Logo",
  },
  { src: npmLogo, name: "npm", url: "https://www.npmjs.com/", alt: "npm Logo" },
  {
    src: discordJsLogo,
    name: "Discord.js",
    url: "https://discord.js.org/",
    alt: "Discord.js Logo",
  },
  {
    src: wordpressLogo,
    name: "WordPress",
    url: "https://wordpress.org/",
    alt: "WordPress Logo",
  },
  {
    src: cypressLogo,
    name: "Cypress",
    url: "https://www.cypress.io/",
    alt: "Cypress Logo",
  },
  { src: jestLogo, name: "Jest", url: "https://jestjs.io/", alt: "Jest Logo" },
  {
    src: tailwindLogo,
    name: "Tailwind CSS",
    url: "https://tailwindcss.com/",
    alt: "Tailwind CSS Logo",
  },
  { src: viteLogo, name: "Vite", url: "https://vitejs.dev/", alt: "Vite Logo" },
  {
    src: vscLogo,
    name: "VS Code",
    url: "https://code.visualstudio.com/",
    alt: "VS Code Logo",
  },
  {
    src: flutterLogo,
    name: "Flutter",
    url: "https://flutter.dev/",
    alt: "Flutter Logo",
  },
];

export default icons;
