import {
  bootstrapLogo,
  cssLogo,
  htmlLogo,
  jsLogo,
  reactLogo,
  sassLogo,
  figmaLogo,
  gitLogo,
  discordJsLogo,
  wordpressLogo,
  cypressLogo,
  jestLogo,
  tailwindLogo,
  viteLogo,
  vscLogo,
  flutterLogo,
} from "../../assets/logos/logoExports.js";

const projects = (t) => [
  {
    title: "Rainydays",
    description: t("rainydays.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/HMAsp/HTML-CSS_CA_HMA_2022",
    builtWith: [
      { src: figmaLogo, title: "Figma", alt: "Figma Logo" },
      { src: htmlLogo, title: "HTML", alt: "HTML Logo" },
      { src: cssLogo, title: "CSS", alt: "CSS Logo" },
      { src: jsLogo, title: "JavaScript", alt: "JavaScript Logo" },
      { src: wordpressLogo, title: "WordPress", alt: "WordPress Logo" },
    ],
    demo: "",
  },
  {
    title: "Community Science Museum",
    description: t("csm.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/Semester_project1",
    builtWith: [
      { src: figmaLogo, title: "Figma", alt: "Figma Logo" },
      { src: htmlLogo, title: "HTML", alt: "HTML Logo" },
      { src: cssLogo, title: "CSS", alt: "CSS Logo" },
    ],
    demo: "",
  },
  {
    title: "Inside The Trip",
    description: t("itt.description"),
    image: "https://via.placeholder.com/150",
    link: "https://www.google.com",
    builtWith: [
      { src: figmaLogo, title: "Figma", alt: "Figma Logo" },
      { src: htmlLogo, title: "HTML", alt: "HTML Logo" },
      { src: cssLogo, title: "CSS", alt: "CSS Logo" },
      { src: jsLogo, title: "JavaScript", alt: "JavaScript Logo" },
      { src: wordpressLogo, title: "WordPress", alt: "WordPress Logo" },
    ],
    demo: "",
  },
  {
    title: "Connotation",
    description: t("connotation.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/css-frameworks-ca",
    builtWith: [
      { src: figmaLogo, title: "Figma", alt: "Figma Logo" },
      { src: htmlLogo, title: "HTML", alt: "HTML Logo" },
      { src: jsLogo, title: "JavaScript", alt: "JavaScript Logo" },
      { src: bootstrapLogo, title: "Bootstrap", alt: "Bootstrap Logo" },
      { src: sassLogo, title: "Sass", alt: "Sass logo" },
    ],
    demo: "https://css-framework-js2.netlify.app/",
    demoNotes: t("connotation.demoNotes"),
  },
  {
    title: "OnlyPineapples",
    description: t("onlypineapples.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/Auction",
    builtWith: [
      { src: figmaLogo, title: "Figma", alt: "Figma Logo" },
      { src: htmlLogo, title: "HTML", alt: "HTML Logo" },
      { src: jsLogo, title: "JavaScript", alt: "JavaScript Logo" },
      { src: bootstrapLogo, title: "Bootstrap", alt: "Bootstrap Logo" },
      { src: sassLogo, title: "Sass", alt: "Sass logo" },
      { src: cypressLogo, title: "Cypress", alt: "Cypress Logo" },
      { src: jestLogo, title: "Jest", alt: "Jest Logo" },
    ],
    demo: "https://hma-sp2-onlypineapples.netlify.app/",
    demoNotes: t("onlypineapples.demoNotes"),
  },
  {
    title: "Cyberstore",
    description: t("cyberstore.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/Auction",
    builtWith: [
      { src: figmaLogo, title: "Figma", alt: "Figma Logo" },
      { src: htmlLogo, title: "HTML", alt: "HTML Logo" },
      { src: jsLogo, title: "JavaScript", alt: "JavaScript Logo" },
      { src: reactLogo, title: "React", alt: "React Logo" },
    ],
    demo: "https://areactecom.netlify.app/",
  },
  {
    title: "Adling",
    description: t("adling.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/AdLing",
    builtWith: [
      { src: discordJsLogo, title: "Discord.js", alt: "Discord.js Logo" },
    ],
  },
  {
    title: "Not-Pong",
    description: t("flutter.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/Flutter-game",
    builtWith: [{ src: flutterLogo, title: "Flutter", alt: "Flutter Logo" }],
    demo: t("flutter.demoNotes"),
    demoNotes: t("flutter.demoNotes"),
  },
  {
    title: "Havens",
    description: t("havens.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/Project-Exam-2",
    builtWith: [
      { src: figmaLogo, title: "Figma", alt: "Figma Logo" },
      { src: htmlLogo, title: "HTML", alt: "HTML Logo" },
      { src: jsLogo, title: "JavaScript", alt: "JavaScript Logo" },
      { src: reactLogo, title: "React", alt: "React Logo" },
      { src: tailwindLogo, title: "Tailwind", alt: "Tailwind Logo" },
      { src: viteLogo, title: "Vite", alt: "Vite Logo" },
      { src: vscLogo, title: "VS Code", alt: "VS Code Logo" },
      { src: gitLogo, title: "Git", alt: "Git Logo" },
    ],
    demo: "https://project-havens.netlify.app/",
    demoNotes: t("havens.demoNotes"),
  },
];

export default projects;
