import {
  bootstrapLogo,
  cssLogo,
  htmlLogo,
  jsLogo,
  reactLogo,
  sassLogo,
  figmaLogo,
  gitLogo,
  githubLogo,
  nodeLogo,
  npmLogo,
  discordJsLogo,
  wordpressLogo,
  cypressLogo,
  jestLogo,
  tailwindLogo,
  viteLogo,
  vscLogo,
  flutterLogo,
} from "../../assets/logos/logoExports.js";

const projects = (t) => [
  {
    title: "Rainydays",
    description: t("rainydays.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/HMAsp/HTML-CSS_CA_HMA_2022",
    builtWith: [
      { src: figmaLogo, title: "Figma" },
      { src: htmlLogo, title: "HTML" },
      { src: cssLogo, title: "CSS" },
      { src: jsLogo, title: "JavaScript" },
      { src: wordpressLogo, title: "WordPress" },
    ],
    demo: "",
  },
  {
    title: "Community Science Museum",
    description: t("csm.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/Semester_project1",
    builtWith: [
      { src: figmaLogo, title: "Figma" },
      { src: htmlLogo, title: "HTML" },
      { src: cssLogo, title: "CSS" },
    ],
    demo: "",
  },
  {
    title: "Inside The Trip",
    description: t("itt.description"),
    image: "https://via.placeholder.com/150",
    link: "https://www.google.com",
    builtWith: [
      { src: figmaLogo, title: "Figma" },
      { src: htmlLogo, title: "HTML" },
      { src: cssLogo, title: "CSS" },
      { src: jsLogo, title: "JavaScript" },
      { src: wordpressLogo, title: "WordPress" },
    ],
    demo: "",
  },
  {
    title: "Connotation",
    description: t("connotation.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/css-frameworks-ca",
    builtWith: [
      { src: figmaLogo, title: "Figma" },
      { src: htmlLogo, title: "HTML" },
      { src: jsLogo, title: "JavaScript" },
      { src: bootstrapLogo, title: "Bootstrap" },
      { src: sassLogo, title: "Sass" },
    ],
    demo: "https://css-framework-js2.netlify.app/",
    demoNotes: t("connotation.demoNotes"),
  },
  {
    title: "OnlyPineapples",
    description: t("onlypineapples.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/Auction",
    builtWith: [
      { src: figmaLogo, title: "Figma" },
      { src: htmlLogo, title: "HTML" },
      { src: jsLogo, title: "JavaScript" },
      { src: bootstrapLogo, title: "Bootstrap" },
      { src: sassLogo, title: "Sass" },
      { src: cypressLogo, title: "Cypress" },
      { src: jestLogo, title: "Jest" },
    ],
    demo: "https://hma-sp2-onlypineapples.netlify.app/",
    demoNotes: t("onlypineapples.demoNotes"),
  },
  {
    title: "Cyberstore",
    description: t("cyberstore.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/Auction",
    builtWith: [
      { src: figmaLogo, title: "Figma" },
      { src: htmlLogo, title: "HTML" },
      { src: jsLogo, title: "JavaScript" },
      { src: reactLogo, title: "React" },
    ],
    demo: "https://areactecom.netlify.app/",
  },
  {
    title: "Adling",
    description: t("adling.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/AdLing",
    builtWith: [{ src: discordJsLogo, title: "Discord.js" }],
  },
  {
    title: "Not-Pong",
    description: t("flutter.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/Flutter-game",
    builtWith: [{ src: flutterLogo, title: "Flutter" }],
    demo: t("flutter.demoNotes"),
    demoNotes: t("flutter.demoNotes"),
  },
  {
    title: "Havens",
    description: t("havens.description"),
    image: "https://via.placeholder.com/150",
    link: "https://github.com/Spookyrumble/Project-Exam-2",
    builtWith: [
      { src: figmaLogo, title: "Figma" },
      { src: htmlLogo, title: "HTML" },
      { src: jsLogo, title: "JavaScript" },
      { src: reactLogo, title: "React" },
      { src: tailwindLogo, title: "Tailwind" },
      { src: viteLogo, title: "Vite" },
      { src: vscLogo, title: "VS Code" },
      { src: gitLogo, title: "Git" },
    ],
    demo: "https://project-havens.netlify.app/",
    demoNotes: t("havens.demoNotes"),
  },
];

export default projects;
